[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-W", "clippy::all",
    "-W", "clippy::pedantic",
    "-W", "clippy::nursery",
    "-W", "clippy::cargo",
    # Allow some pedantic lints that are too strict
    "-A", "clippy::module_name_repetitions",
    "-A", "clippy::missing_errors_doc",
    "-A", "clippy::missing_panics_doc",
]
